Add STM32L4R5 to CMAKE config and to config script
iml130/iree-bare-metal-arm pull request #198
Opened 2022-08-25 15:57 UTC by marbre

Depends on #196 and #197.

2022-08-26 07:47 UTC, lucas-camp requested changes

2022-08-26 07:47 UTC, lucas-camp commented on build_tools/configure_build.sh
> +    echo "  'stm32f4r5'"
```suggestion
    echo "  'stm32l4r5'"
```

2022-08-26 09:40 UTC, marbre commented on build_tools/configure_build.sh
> +    echo "  'stm32f4r5'"
Fixed.

2022-08-29 11:28 UTC, lucas-camp approved these changes

2022-08-29 12:24 UTC, merged