Add custom memory configuration
iml130/iree-bare-metal-arm pull request #21
Opened 2021-11-15 10:55 UTC by heidebro

Add linker scripts both for CMSIS and libopencm3 that increase the size
of the ROM and RAM to 256M for the target board.

Add appropriate Renode configuration files both for the original and
the extended memory configuration.

Amend READMEs accordingly.

Co-authored-by: Lucas Camphausen <lucas.camphausen@iml.fraunhofer.de>

2021-11-15 11:12 UTC, marbre requested changes
Some first remarks. I would strongly request to split into several commits as we import several files from different repos. We also need to make sure that license/copyright information is provided correctly. Let's take that discussions f2f.

2021-11-15 11:12 UTC, marbre commented on README.md
> +```
With only `PATH_TO_LINKER_SCRIPT` changed, I don't see a need to replicate the whole instructions. This only makes it harder to keep our docs up-to-date. I would strongly prefer if we can drop the duplication.

2021-11-15 11:12 UTC, marbre commented on renode/stm32f4-base.repl
> +    size: 0x20000
Missing EOL.

2021-11-15 11:12 UTC, marbre commented on renode/stm32f4-base.resc
> +runMacro $reset
Missing EOL.

2021-11-15 11:12 UTC, marbre commented on renode/stm32f4-custom.resc
> +runMacro $reset
Missing EOL.

2021-11-15 11:12 UTC, marbre commented on renode/stm32f4-base.resc
> +:description: This script runs Contiki on STM32F4 Discovery.
The description seems outdated?

2021-11-15 13:48 UTC, marbre commented on build_tools/stm32f4/stm32f4-discovery-libopencm3-custom.ld
> +/* Linker script for ST STM32F4DISCOVERY (STM32F407VG, 1024K flash, 128K RAM). */
```suggestion
/* Linker script for a custom STM32F4 (STM32F407VG, 256 MB flash, 256 MB RAM). */
```

2021-11-15 13:50 UTC, marbre commented on build_tools/stm32f4/stm32f407-cmsis-custom.ld
> + * @file     stm32f407.ld
```suggestion
 * @file     stm32f407-cmsis-custom.ld
```

2021-11-15 13:51 UTC, marbre commented on build_tools/stm32f4/stm32f407-cmsis-custom.ld
> + *  Adapted from the stm32f407.ld linker script of CMSIS.
```suggestion
 *  Adopted from the stm32f407.ld linker script of CMSIS.
```

2021-11-15 13:52 UTC, marbre commented on build_tools/stm32f4/stm32f407-cmsis-custom.ld
> + *  "stm32f407-cmsis-base" and "stm32f407-cmsis-custom".
Seems outdated?

2021-11-18 08:30 UTC, heidebro commented
Superseded by PR #22

2021-11-18 08:30 UTC, closed without merging