Revise linker script for CMSIS
iml130/iree-bare-metal-arm pull request #25
Opened 2021-11-18 14:28 UTC by lucas-camp

This splits the linker script for CMSIS and adds a linker script with high memory configuration.

2021-11-18 18:45 UTC, marbre requested changes
Thanks for the work. Some minor remarks.

2021-11-18 18:45 UTC, marbre commented on build_tools/stm32f4xx-cmsis-base.ld
> + * @file     stm32f407.ld
```suggestion
 * @file     stm32f4xx-cmsis-base.ld
```

2021-11-18 18:45 UTC, marbre commented on build_tools/stm32f4xx-cmsis-base.ld
> + * Copyright (c) 2009-2021 Arm Limited. All rights reserved.
```suggestion
 * Copyright (c) 2009-2021 Arm Limited. All rights reserved.
 * Copyright (c) 2021 Fraunhofer-Gesellschaft zur Förderung der angewandten Forschung e.V.
```

2021-11-18 18:45 UTC, marbre commented on build_tools/stm32f4xx-highmem-cmsis.ld
> + * Copyright (c) 2009-2021 Arm Limited. All rights reserved.
```suggestion
 * Copyright (c) 2009-2021 Arm Limited. All rights reserved.
 * Copyright (c) 2021 Fraunhofer-Gesellschaft zur Förderung der angewandten Forschung e.V.
```

2021-11-18 18:45 UTC, marbre commented on build_tools/stm32f4xx-highmem-cmsis.ld
> + * @file     stm32f407.ld
```suggestion
 * @file     stm32f4xx-highmem-cmsis.ld
```

2021-11-18 18:45 UTC, marbre commented on build_tools/third_party/cmsis_device_f4/CMakeLists.txt
> +# allow ld to find generic linker script
```suggestion
# Allow ld to find generic linker script
```

2021-11-22 09:54 UTC, marbre commented on build_tools/README.md
> +The `stm32f4xx-cmsis-base.ld` and `stm32f407-cmsis.ld` linker scripts are based on the the [`gcc_arm.ld`](https://github.com/ARM-software/CMSIS_5/blob/ca1b514243d8e69f1a8190e59de4b0c4ea6bdcaa/Device/
```suggestion
The `stm32f4xx-cmsis-base.ld` and `stm32f407-cmsis.ld` linker scripts are based on the the [`gcc_arm.ld`](https://github.com/ARM-software/CMSIS_5/blob/ca1b514243d8e69f1a8190e59de4b0c4ea6bdcaa/Device/_Template_Vendor/Vendor/Device/Source/GCC/gcc_arm.ld) linker script from the [ARM-software/CMSIS_5](https://github.com/ARM-software/CMSIS_5) repository. The `gcc_arm.ld` linker script was split, such that common parts are in `stm32f4xx-cmsis-base.ld` whereas the memory layout is defined in `stm32f407-cmsis.ld`.
```

2021-11-22 10:34 UTC, lucas-camp commented on build_tools/README.md
> +The `stm32f4xx-cmsis-base.ld` and `stm32f407-cmsis.ld` linker scripts are based on the the [`gcc_arm.ld`](https://github.com/ARM-software/CMSIS_5/blob/ca1b514243d8e69f1a8190e59de4b0c4ea6bdcaa/Device/
Should be fixed now.

2021-11-22 11:39 UTC, merged

2021-11-22 11:40 UTC, marbre commented
Forgot to approve before merging, but looks good to me!